
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/pconrad-jpa03-it
owner: ucsb-cs156-s24
repo_name: pconrad-jpa03-it
pull_requests: [{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pcAp-wiremockoauth-refactor","number":3,"title":"Pc ap wiremockoauth refactor","url":"https://github.com/ucsb-cs156-s24/pconrad-jpa03-it/pull/3"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"ap-wiremockoauth","number":2,"title":"ap-add maven profile to run h2 with frontend, working simple test","url":"https://github.com/ucsb-cs156-s24/pconrad-jpa03-it/pull/2"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"ap-wiremockoauth","number":1,"title":"Ap wiremockoauth","url":"https://github.com/ucsb-cs156-s24/pconrad-jpa03-it/pull/1"}]
